/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-18 09:10:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mul.cam.a.dto.UserDto;
import mul.cam.a.dto.EventDto;

public final class layout_002dtiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/BusyBee_MERGED/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BusyBee/WEB-INF/lib/tiles-jsp-3.0.7.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1470892568000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.7.jar", Long.valueOf(1676953296043L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mul.cam.a.dto.UserDto");
    _jspx_imports_classes.add("mul.cam.a.dto.EventDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	UserDto login = (UserDto)session.getAttribute("login");


      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Busy bee</title>\n");
      out.write("<!-- 부트스트랩 JavaScript 및 의존성 -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.3/dist/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- jQuery -->\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>	\n");
      out.write("	<!-- jQuery UI CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("<!-- Moment.js -->\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("\n");
      out.write("<!-- Moment.js -->\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>\n");
      out.write("\n");
      out.write("<!-- 원하는 글꼴 추가 -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Dongle:wght@300;400;700&family=Jua&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Font Awesome 아이콘 -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- FullCalendar CSS -->\n");
      out.write("<link rel='stylesheet'\n");
      out.write("	href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css' />\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap Datepicker -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- timepicker -->\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css\">\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://bootswatch.com/5/minty/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("span {\n");
      out.write("	float: right;\n");
      out.write("	margin-right: 3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\n");
      out.write("	margin: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	border-collapse: collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write("td {\n");
      out.write("	vertical-align: top;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div align=\"center\">\n");
      out.write("\n");
      out.write("		<table>\n");
      out.write("\n");
      out.write("			<!-- header -->\n");
      out.write("			<tr align=\"center\" style=\"background-color: #fff7e1; color: gray;\">\n");
      out.write("				<td><header>\n");
      out.write("						<img src=\"images/logo.png\" width=\"250px\" height=\"40px\"\n");
      out.write("							style=\"float: left; margin: 20px;\">\n");
      out.write("					</header></td>\n");
      out.write("\n");
      out.write("				<td style=\"height: 5%\">\n");
      out.write("					<div style=\"float: right; margin-right: 30px; margin-top: 15px\">\n");
      out.write("					\n");
      out.write("						<!-- user Name 받아오기     \n");
      out.write("    					 <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> -->\n");
      out.write("						<!--  user 상태 메시지\n");
      out.write("						<span style=\"color: gray;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> -->\n");
      out.write("\n");
      out.write("						<!-- 임시 -->\n");
      out.write("						<span style=\"font-size: 15px;\">");
      out.print(login.getName());
      out.write('(');
      out.print(login.getId() );
      out.write(")</span> <br /> \n");
      out.write("						<span style=\"color: #938046; font-size: 13px;\">");
      out.print(login.getProfMsg() );
      out.write("</span>\n");
      out.write("\n");
      out.write("						<!-- 로그아웃 , 회원정보 수정-->\n");
      out.write("						<br /> \n");
      out.write("						<a style=\"float: right; margin-right: 5px;\"	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logoutUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">로그아웃</a> \n");
      out.write("						<a style=\"float: right; margin-right: 5px;\" href=\"goUserinfo.do\">정보 수정</a>\n");
      out.write("					</div>\n");
      out.write("					 	<!-- user image -->\n");
      out.write("					<div style=\"float: right; margin: 5px; margin-right: 30px;\">\n");
      out.write("						<img src=\"/busyBeeImg/");
      out.print(login.getProfPic_Server() );
      out.write("\" width=\"70px\" height=\"70px\"\n");
      out.write("							style=\"border-radius: 50%;\">\n");
      out.write("					</div>\n");
      out.write("				</td>\n");
      out.write("				\n");
      out.write("		</tr>\n");
      out.write("		\n");
      out.write("		<!-- 메뉴 이동 네비게이션 -->\n");
      out.write("		<tr>\n");
      out.write("		<td colspan=\"2\">\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light bg-light\" style=\"margin-bottom: 0px;\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarColor03\">\n");
      out.write("				<ul class=\"navbar-nav me-auto\" style=\"font-size: 14px\">\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\">메인\n");
      out.write("							<span class=\"visually-hidden\">(current)</span>\n");
      out.write("					</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">임시 게시판</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">임시 일정관리</a>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">임시 채팅</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"goAddgroup.do\">그룹 생성</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"goMygroup.do\">내 그룹</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"goSearchgroup.do\">그룹 검색</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"goNoti.do\">그룹 알림</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	</td>\n");
      out.write("	</tr>\n");
      out.write("		\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- menu 영역 -->\n");
      out.write("			<tr>\n");
      out.write("				<td align=\"left\" valign=\"top\"\n");
      out.write("					style=\"background-color: #fffaea; padding: 15px;\" height=\"765px\"\n");
      out.write("					width=\"10%\">\n");
      out.write("					");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("\n");
      out.write("				<!-- content 영역 -->\n");
      out.write("				<td valign=\"top\" style=\"padding: 10px;\">\n");
      out.write("				");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("\n");
      out.write("			</tr>\n");
      out.write("\n");
      out.write("			<!-- footer 영역 -->\n");
      out.write("			<tr align=\"right\" style=\"background-color: #fff7e1; color: #938046;\">\n");
      out.write("				<td colspan=\"5\" height=\"25px\">\n");
      out.write("				");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("\n");
      out.write("			</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout-tiles.jsp(187,5) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("menu");
      _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    try {
      _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout-tiles.jsp(191,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f1.setName("content");
      _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    try {
      _jspx_th_tiles_005finsertAttribute_005f2.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout-tiles.jsp(199,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f2.setName("footer");
      _jspx_th_tiles_005finsertAttribute_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    }
    return false;
  }
}
