/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-18 07:56:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.noTiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regi1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입(1/2)</title>\n");
      out.write("\n");
      out.write("<!-- AJAX -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<form action=\"regi2.do\" id=\"frm\" method=\"post\">\n");
      out.write("이메일 : <input type=\"text\" id=\"email1\">@\n");
      out.write("<select id=\"email2\" onchange=\"ifdirect()\">\n");
      out.write("	<option>naver.com</option>\n");
      out.write("	<option>daum.net</option>\n");
      out.write("	<option>gmail.com</option>\n");
      out.write("	<option>hanmail.com</option>\n");
      out.write("	<option>yahoo.co.kr</option>\n");
      out.write("	<option value=\"direct\">직접 입력</option>\n");
      out.write("</select>\n");
      out.write("<div id=\"directEmail\">\n");
      out.write("<input type=\"hidden\" id=\"isDirect\" value=\"no\">\n");
      out.write("</div>\n");
      out.write("<button type=\"button\" id=\"emailCert\" onclick=\"doCert()\">인증메일 발송</button>\n");
      out.write("인증번호 : <input type=\"text\" id=\"certNum\" disabled=\"disabled\" maxlength=\"6\"> <button type=\"button\" id=\"check\" onclick=\"checkCert()\">인증번호 확인</button>\n");
      out.write("<input type=\"hidden\" id=\"cert_OK\">\n");
      out.write("\n");
      out.write("아이디 : <input type=\"text\" id=\"id\" name=\"id\">\n");
      out.write("<h3 id=\"idCheck\"></h3>\n");
      out.write("\n");
      out.write("비밀번호 : <input type=\"password\" id=\"pwd1\" name=\"password\">\n");
      out.write("<h3 id=\"pwdCheck1\"></h3>\n");
      out.write("비밀번호 확인:<input type=\"password\" id=\"pwd2\">\n");
      out.write("<h3 id=\"pwdCheck2\"></h3>\n");
      out.write("\n");
      out.write("<input type=\"hidden\" id=\"email\" name=\"email\">\n");
      out.write("<input type=\"hidden\" id=\"id_OK\">\n");
      out.write("<input type=\"hidden\" id=\"pwd1_OK\">\n");
      out.write("<input type=\"hidden\" id=\"pwd2_OK\">\n");
      out.write("\n");
      out.write("<button type=\"button\" onclick=\"go_regi2()\">다음</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var userEmail;\n");
      out.write("var authkey;\n");
      out.write("\n");
      out.write("var id_OK = document.getElementById(\"id_OK\").value;\n");
      out.write("var pwd1_OK = document.getElementById(\"pwd1_OK\").value;\n");
      out.write("var pwd2_OK = document.getElementById(\"pwd2_OK\").value;\n");
      out.write("var cert_OK = document.getElementById(\"cert_OK\").value;\n");
      out.write("cert_OK = false;\n");
      out.write("\n");
      out.write("// EMAIL 인증\n");
      out.write("function ifdirect(){\n");
      out.write("	\n");
      out.write("	if ($(\"#email2\").val()=='direct'){\n");
      out.write("		var directE = \"<input type='text' id='email3'>\"\n");
      out.write("		$(\"#directEmail\").append(directE);\n");
      out.write("		$(\"#isDirect\").val('yes');\n");
      out.write("	} else {\n");
      out.write("		$(\"#email3\").remove();\n");
      out.write("		$(\"#isDirect\").val('no');\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function doCert() {\n");
      out.write("	\n");
      out.write("	// 이메일 정규식\n");
      out.write("	var emailValid = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\n");
      out.write("	\n");
      out.write("	if ($(\"#isDirect\").val()=='no') {\n");
      out.write("		userEmail = $(\"#email1\").val() + '@' + $(\"#email2\").val();\n");
      out.write("		if(!emailValid.test(userEmail)) {\n");
      out.write("			alert('유효한 이메일을 입력해주세요.');\n");
      out.write("			$(\"#email1\").val('');\n");
      out.write("			$(\"#email2\").val('');\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("	} else {\n");
      out.write("		userEmail = $(\"#email1\").val() + '@' + $(\"#email3\").val();\n");
      out.write("		if(!emailValid.test(userEmail)) {\n");
      out.write("			alert('유효한 이메일을 입력해주세요.');\n");
      out.write("			$(\"#email1\").val('');\n");
      out.write("			$(\"#email2\").val('');\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	var checkCert = $(\"#certNum\").val();\n");
      out.write("	var check3 = true;\n");
      out.write("	\n");
      out.write("	$.ajax({\n");
      out.write("		url : \"select3.do\",\n");
      out.write("		async:false,\n");
      out.write("		type : 'get',\n");
      out.write("		data : {\"cert_email\" : userEmail},\n");
      out.write("		success : function(msg) {\n");
      out.write("			if(msg==\"cert3_FAIL\"){\n");
      out.write("				alert('일일 최대 인증횟수 3회를 초과했습니다. 다음에 다시 시도해주세요.');\n");
      out.write("				$(\"#certNum\").attr('disabled', true);\n");
      out.write("				$(\"#emailCert\").attr('disabled', true);\n");
      out.write("				$(\"#check\").attr('disabled', true);\n");
      out.write("				location.href='loginMain.do';\n");
      out.write("				check3 = false;\n");
      out.write("			}\n");
      out.write("		},\n");
      out.write("		error : function(){\n");
      out.write("			alert('error');\n");
      out.write("		}\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	if (!check3) {\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	$.ajax({\n");
      out.write("			url : \"mailCheck.do\",\n");
      out.write("			type : 'get',\n");
      out.write("			data : {\"email\" : userEmail, \"purpose\" : \"regi\"},\n");
      out.write("			success : function(data) {\n");
      out.write("				$(\"#certNum\").attr('disabled',false);\n");
      out.write("				alert('인증번호가 전송되었습니다. 인증은 일일 3회까지 가능합니다.');\n");
      out.write("				authkey = data;\n");
      out.write("			},\n");
      out.write("			error : function(){\n");
      out.write("				alert('error');\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkCert(){\n");
      out.write("	\n");
      out.write("	$.ajax({\n");
      out.write("		type : 'get',\n");
      out.write("		url : \"selectCert.do\",\n");
      out.write("		data : {\"cert_email\" : userEmail, \"authkey\" : $(\"#certNum\").val()},\n");
      out.write("		success : function(msg) {\n");
      out.write("			if(msg!=null && msg!=\"\"){\n");
      out.write("				if(msg==\"cert_SUCCESS\") {\n");
      out.write("					alert(\"인증되었습니다.\");\n");
      out.write("					$(\"#email1\").attr('disabled', true);\n");
      out.write("					$(\"#email2\").attr('disabled', true);\n");
      out.write("					$(\"#certNum\").attr('disabled', true);\n");
      out.write("					$(\"#emailCert\").attr('disabled', true);\n");
      out.write("					$(\"#check\").attr('disabled', true);\n");
      out.write("					cert_OK = true;\n");
      out.write("					$(\"#email\").val(userEmail);\n");
      out.write("				} else {\n");
      out.write("					alert(\"잘못된 인증번호입니다. 다시 확인해주세요\");\n");
      out.write("					cert_OK = false;\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		},\n");
      out.write("		error : function() {\n");
      out.write("			alert('error');\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("// ID\n");
      out.write("$(\"#id\").keyup(function(e){\n");
      out.write("	\n");
      out.write("	let key = e.key || e.keyCode;\n");
      out.write("	\n");
      out.write("	// ID 유효성 검사\n");
      out.write("	var idValid = /^[a-zA-z0-9]{6,12}$/;\n");
      out.write("	\n");
      out.write("	if($(\"#id\").val()==\"\") {\n");
      out.write("		$(\"#idCheck\").text('');\n");
      out.write("		id_OK=false;\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if(key==\" \" || key==32) {\n");
      out.write("		alert('아이디에는 공백이 들어갈 수 없습니다.');\n");
      out.write("		$(\"#id\").val('');\n");
      out.write("		$(\"#idCheck\").text('');\n");
      out.write("		id_OK=false;\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	$.ajax({\n");
      out.write("		url:\"idCheck.do\",\n");
      out.write("		type:\"post\",\n");
      out.write("		data:{\"id\":$(\"#id\").val()},\n");
      out.write("		success:function(idCheck_Msg) {\n");
      out.write("			if(idCheck_Msg!=null && idCheck_Msg!=\"\") {\n");
      out.write("				if(idCheck_Msg==\"idCheck_SUCCESS\") {\n");
      out.write("					if(!idValid.test($(\"#id\").val())) {\n");
      out.write("						$(\"#idCheck\").text('ID는 6~12자, 영문 대소문자와 숫자로 설정해주세요.');\n");
      out.write("						id_OK=false;\n");
      out.write("					} else {\n");
      out.write("						$(\"#idCheck\").text('사용가능한 ID입니다.');\n");
      out.write("						id_OK=true;\n");
      out.write("					}\n");
      out.write("\n");
      out.write("				} else {\n");
      out.write("					$(\"#idCheck\").text('이미 존재하는 ID입니다.');\n");
      out.write("					id_OK=false;\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		},\n");
      out.write("		error:function(){\n");
      out.write("			alert('error');\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("});\n");
      out.write("\n");
      out.write("// PWD(1/2)\n");
      out.write("$(\"#pwd1\").keyup(function(e){\n");
      out.write("	\n");
      out.write("	let key = e.key || e.keyCode;\n");
      out.write("\n");
      out.write("	if($(\"#pwd1\").val()==\"\") {\n");
      out.write("		$(\"#pwdCheck1\").text('');\n");
      out.write("		$(\"#pwdCheck2\").text('');\n");
      out.write("		pwd1_OK=false;\n");
      out.write("		pwd2_OK=false;\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if(key==\" \" || key==32) {\n");
      out.write("		alert('비밀번호에는 공백이 들어갈 수 없습니다.');\n");
      out.write("		$(\"#pwd1\").val('');\n");
      out.write("		$(\"#pwdCheck1\").text('');\n");
      out.write("		pwd1_OK=false;\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if($(\"#pwd1\").val()==$(\"#pwd2\").val()) {\n");
      out.write("		$(\"#pwdCheck2\").text('동일합니다.');\n");
      out.write("		pwd2_OK=true;\n");
      out.write("	} else{\n");
      out.write("		$(\"#pwdCheck2\").text('');\n");
      out.write("		pwd2_OK=false;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// PWD 유효성 검사\n");
      out.write("	var pwd1 = $(\"#pwd1\").val();\n");
      out.write("	var numValid = pwd1.search(/[0-9]/g);\n");
      out.write("	var engValid = pwd1.search(/[a-z]/ig);\n");
      out.write("	var speValid = pwd1.search(/[`~!@@#$%^&*|₩₩₩'₩\";:₩/?]/gi);\n");
      out.write("	\n");
      out.write("	if (pwd1.length<8 || pwd1.length>20) {\n");
      out.write("		$(\"#pwdCheck1\").text('비밀번호는 6~20자로 설정해주세요.');\n");
      out.write("		pwd1_OK=false;\n");
      out.write("	} else if(numValid < 0 || engValid < 0 || speValid < 0 ){\n");
      out.write("		$(\"#pwdCheck1\").text('비밀번호에는 숫자, 영문, 특수문자가 모두 포함되어있어야 합니다.');\n");
      out.write("		pwd1_OK=false;\n");
      out.write("	} else {\n");
      out.write("		$(\"#pwdCheck1\").text('사용가능한 비밀번호입니다.');\n");
      out.write("		pwd1_OK=true;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("});\n");
      out.write("\n");
      out.write("// PWD(2/2)\n");
      out.write("\n");
      out.write("$(\"#pwd2\").keyup(function(){\n");
      out.write("	\n");
      out.write("	if($(\"#pwd2\").val()==\"\") {\n");
      out.write("		$(\"#pwdCheck2\").text('');\n");
      out.write("		pwd2_OK=false;\n");
      out.write("		return;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if($(\"#pwd1\").val()!=$(\"#pwd2\").val()) {\n");
      out.write("		$(\"#pwdCheck2\").text('동일한 비밀번호를 입력해주세요.');\n");
      out.write("		pwd2_OK=false;\n");
      out.write("	} else {\n");
      out.write("		$(\"#pwdCheck2\").text('동일합니다.');\n");
      out.write("		pwd2_OK=true;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("function go_regi2() {\n");
      out.write("\n");
      out.write("	if (!cert_OK) {\n");
      out.write("		alert('이메일 인증을 진행해주세요.');\n");
      out.write("	} else if(!id_OK) {\n");
      out.write("		alert('아이디 중복 여부를 확인해주세요.');\n");
      out.write("		$(\"#id\").focus();\n");
      out.write("	} else if((!pwd1_OK)) {\n");
      out.write("		alert('사용 가능한 비밀번호인지 확인해주세요.');\n");
      out.write("		$(\"#pwd1\").focus();		\n");
      out.write("	} else if((!pwd2_OK)) {\n");
      out.write("		alert('동일한 비밀번호를 입력했는지 확인해주세요.');\n");
      out.write("		$(\"#pwd2\").focus();		\n");
      out.write("	} else {\n");
      out.write("		$(\"#frm\").submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
